$(document).ready(function(){var d;lang_global=localStorage.lang;document.addEventListener("deviceready",function(){d=window.sqlitePlugin.openDatabase({name:"flags.db",location:"default"});d.transaction(function(n){n.executeSql('SELECT * FROM "flags" WHERE "id" = 1',[],function(n,r){window.page_str=function(){localStorage.pg_str=document.getElementById("main_content").innerHTML};var p=function(){for(var b=[],a,f=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),c=0;c<f.length;c++)a=
f[c].split("="),b.push(a[0]),b[a[0]]=a[1];return b}(),k=p.flag_id,h=p.cflags;h&&(h=h.replace("#",""));$.getScript("bootstrap/js/local/"+lang_global+".js",function(){window.lg=languages;document.getElementById("title_flags").innerHTML=lg.main2;var b="yes"==h?'<a class="btn btn-block btn-info" type="button" href="flags.html">'+lg.btn_flag1+"</a>":'<a class="btn btn-block btn-info" type="button" href="flags.html?cflags=yes">'+lg.btn_flag2+"</a>";document.getElementById("but").innerHTML=b;$("input[id=search]").attr("placeholder",
lg.inp_s)});window.fastsearch=function(b){var a=document.getElementById(b).value;a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();0<a.length?d.readTransaction(function(b){b.executeSql('SELECT * FROM "flags" WHERE "rus" LIKE \'%'+a+"%' OR \"eng\" LIKE '%"+a+"%'",[],function(b,f){var c=f.rows.length,g;for(g=0;g<c;g++){"rus"==lang_global&&(tex=f.rows.item(g).rus);"eng"==lang_global&&(tex=f.rows.item(g).eng);var e=0==g?"<a onclick=\"page_str();localStorage['search_str']='"+a+'\';localStorage[\'search_pos\']=window.pageYOffset;" class="btn btn-block btn-default" type="button" href="flags.html?flag_id='+
f.rows.item(g).id+'">'+tex+"</a>":e+"<a onclick=\"page_str();localStorage['search_str']='"+a+'\';localStorage[\'search_pos\']=window.pageYOffset;" class="btn btn-block btn-default" type="button" href="flags.html?flag_id='+f.rows.item(g).id+'">'+tex+"</a>"}void 0===e&&(e="\u041f\u043e\u0438\u0441\u043a \u043d\u0435 \u0434\u0430\u043b \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u043e\u0432");document.getElementById("search_result").innerHTML=e+"<hr>"})}):document.getElementById("search_result").innerHTML=
""};if(k)k=k.replace("#",""),d.readTransaction(function(b){b.executeSql('SELECT * FROM "flags" WHERE "id" = '+k,[],function(b,a){var c=a.rows.item(0).rus;"rus"==lang_global&&(c=a.rows.item(0).rus);"eng"==lang_global&&(c=a.rows.item(0).eng);c='<div class="alert alert-info" role="alert" style="padding: 5px 15px 5px 15px;"><h3 style="margin: 3px;">'+c+'</h3></div><a href="img/flags/'+a.rows.item(0).img+'" class="thumbnail"><img src="img/flags/'+a.rows.item(0).img+'" style="border:2px solid;"></a>';document.getElementById("countries").innerHTML=
c})});else{var l=function(a,d){for($i=a;$i<=d;$i++)var b=$i==a?'<a id="hr_cont'+$i+'"></a>':b+'<a id="hr_cont'+$i+'"></a>';var c=document.getElementById("countries").innerHTML;document.getElementById("countries").innerHTML=c+b;from2=a-1;$("div[id=countries]").attr("count",d);q(from2,"50",h)},q=function(a,h,f){d.readTransaction(function(b){b.executeSql('SELECT * FROM flags ORDER BY "rus" ASC LIMIT '+a+", "+h,[],function(b,c){var g=c.rows.length,e;for(e=0;e<g;e++){var d=e+1+a;"rus"==lang_global&&(tex=
c.rows.item(e).rus);"eng"==lang_global&&(tex=c.rows.item(e).eng);"yes"==f?($("a[id=hr_cont"+d+"]").attr({onclick:"page_str();localStorage['search_pos']=window.pageYOffset;",href:"flags.html?flag_id="+c.rows.item(e).id,"class":"col-lg-2 col-md-3 col-sm-4 col-xs-6 thumbnail"}),document.getElementById("hr_cont"+d).innerHTML='<img src="img/flags/'+c.rows.item(e).img+'" style="border:1px solid;height:100px;">'):($("a[id=hr_cont"+d+"]").attr({onclick:"page_str();localStorage['search_pos']=window.pageYOffset;",
href:"flags.html?flag_id="+c.rows.item(e).id,"class":"btn btn-block btn-default",type:"button"}),document.getElementById("hr_cont"+d).innerHTML=tex)}})})};if(localStorage.pg_str){document.getElementById("main_content").innerHTML=localStorage.pg_str;localStorage.search_str&&$("input[id=search]").attr("value",localStorage.search_str);$(document).ready(function(){var a=localStorage.search_pos;a=parseFloat(a);localStorage.search_pos=0;scrollTo(0,a)});localStorage.search_str="";localStorage.pg_str="";
var a=$("div[id=countries]").attr("count");window.attr_count=parseFloat(a);var m=$(window).height();$(document).on("scroll",function(){$("a[id=hr_cont"+(a-5)+"]").each(function(){var b=$(this);b=b.offset().top+b.height();$(document).scrollTop()+m>=b&&(a=parseFloat(a),b=a+1,a+=50,300>=a&&(254<a&&(a=254),l(b,a)))})})}else(a=$("div[id=countries]").attr("count"))?q(0,a,h):($("div[id=countries]").attr("count","50"),a=50,m=$(window).height(),$(document).on("scroll",function(){$("a[id=hr_cont"+(a-5)+"]").each(function(){var b=
$(this);b=b.offset().top+b.height();$(document).scrollTop()+m>=b&&(b=a+1,a+=50,300>=a&&(254<a&&(a=254),l(b,a)))})}),l("1","50"))}},function(d){$.getScript("bootstrap/js/dump/flags.js",function(){})})})},!1)});